<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.16.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.0.1" />
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
    <PackageReference
      Include="Microsoft.Azure.Functions.Worker.Extensions.Storage"
      Version="5.0.0"
    />
    <PackageReference
      Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB"
      Version="4.0.0"
    />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="3.6.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
    <PackageReference Include="Azure.Identity" Version="1.17.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrderProcessor.Domain\OrderProcessor.Domain.csproj" />
    <ProjectReference Include="..\OrderProcessor.Services\OrderProcessor.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
